# Generated by Django 4.2.9 on 2024-01-04 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('priority', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='WebResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('siteName', models.CharField(max_length=255)),
                ('siteID', models.IntegerField(default=0)),
                ('siteURL', models.CharField(max_length=1000)),
                ('siteKeywords', models.ManyToManyField(to='capstoneapp.keyword')),
            ],
        ),
    ]
