# Generated by Django 4.2.9 on 2024-03-22 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstoneapp', '0002_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='myDescription',
            field=models.TextField(null=True),
        ),
    ]
