# Generated by Django 4.2.9 on 2024-03-24 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstoneapp', '0003_message_mydescription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='myDescription',
        ),
        migrations.AddField(
            model_name='message',
            name='link1',
            field=models.CharField(default='', max_length=100000),
        ),
        migrations.AddField(
            model_name='message',
            name='link2',
            field=models.CharField(default='', max_length=100000),
        ),
        migrations.AddField(
            model_name='message',
            name='link3',
            field=models.CharField(default='', max_length=100000),
        ),
        migrations.AddField(
            model_name='message',
            name='res1',
            field=models.CharField(default='', max_length=100000),
        ),
        migrations.AddField(
            model_name='message',
            name='res2',
            field=models.CharField(default='', max_length=100000),
        ),
        migrations.AddField(
            model_name='message',
            name='res3',
            field=models.CharField(default='', max_length=100000),
        ),
    ]
